"""
ProjectEuler.net #12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?

"""

TARGET = 500

def main():
    divisors = set()
    t = 0
    triangle = 0
    s = 1
    count = 0
    while(True):
        # Move to next triangle number
        t += 1
        triangle += t
        # Only check up to sqrt of number
        # After sqrt there are only repeats (ex. 4,7, then 7,4 later.)
        while s**2 < triangle:
            s += 1
        # Always divisible by 1 and number
        divisors.add(1)
        divisors.add(triangle)
        for i in range(2,s+1):
            div, mod = divmod(triangle, i)
            # If evenly divisible, add number and result to divisors
            if mod == 0:
                divisors.add(i)
                divisors.add(div)
        # Get total count of divisors
        count = len(divisors)
        if count > TARGET:
            break
        # Reset values
        divisors.clear()
    print(triangle)

if __name__=='__main__':
    main()
