"""
ProjectEuler.net #2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

LIMIT = 4_000_000

def get_even_fibonacci_numbers():
	result = []
	a, b = 1, 2
	while a <= LIMIT:
		if a % 2 == 0:
			result.append(a)
		a, b = b, a + b
	return result

def main():
	even_numbers = get_even_fibonacci_numbers()
	value = sum(even_numbers)
	print(value)
		
if __name__=='__main__':
	main()